面談日程を承認or却下する機能の実装
tkr-ld/e-navigator pull request #10
Opened 2019-03-26 06:52 UTC by tkr-ld

やりたかったこと
---
- トップページに自分以外のユーザーの表示
- 面接官用の面接日程一覧ページの作成
- 面接日程を承認or拒否できるようにする

やったこと
----
- ユーザー一覧表示機能の実装
- ログインユーザーの面接日程かどうかで表示内容の切り替え
- 面接日程の承認画面の実装
- 承認機能の実装
- 自分の面接一覧を表示したときに保留の面接のみ、編集・削除ができるように変更
- ナビバーの変更（トップページへリンクの追加）

動作確認方法
---
- [ ] ログインし、トップページに自分以外のユーザー一覧が表示されていることを確認する
- [ ] 面接一覧から面接日程を確定する
- [ ] 再度面接一覧にいき、設定した面接日程になっていることを確認する
- [ ] 自分の面接一覧にいく
- [ ] 他のユーザーの面接一覧画面と表示内容が違うことを確認する
- [ ] 新規面接を作成する
- [ ] 保留の面接以外は、編集と削除のリンクが不活性になっていることを確認する

その他
---
よろしくお願いします。

2019-03-27 02:08 UTC, pokotyamu requested changes
レビューコメント付けました！
質問している部分もあるので、ご回答いただけると嬉しいです 🙏

2019-03-27 02:08 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    if interview.present?
`if xxx.present?` は `unless xxx` とも書くことができますね 👀

2019-03-27 02:08 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  def after_update(interview)
`after_update` か 🤔 
後処理的に見えてしまったな。
例えば、 

```
if interview.update
else
  # こっちは update した後ではない？
end
```

`after_update` だと少し意味が広すぎると思います。(そもそも `after_action` っぽく見える)
`update_success` なり、 `update_success_redirect` なり、更新に成功したという表現を足してみると良いような気がしますね。

2019-03-27 02:08 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +  before_action :correct_user, only: [:destroy]
ここ、 `#edit` と `#update` を外したのって理由ありますか？

2019-03-27 02:08 UTC, pokotyamu commented on config/routes.rb
> +          patch :approve
インデントが 4つになってますね 👀 
ruby はインデント2つです！

2019-03-27 02:08 UTC, pokotyamu commented on config/routes.rb
> +          patch :approve
ここ、 PUT じゃなくて、 PATCH メソッドを選択したのって理由ありますか？ 👀

2019-03-27 02:08 UTC, pokotyamu commented on app/models/interview.rb
> +    if self.update(status: :approval)
ここの self って必要です？ 👀

2019-03-27 02:08 UTC, pokotyamu commented on app/models/interview.rb
> +    if self.update(status: :approval)
enum で設定してあるとこんな風なヘルパーも書くことができますよ

```ruby 
if approval! # => approval な状態にする
  xxxx
end
```

2019-03-27 02:08 UTC, pokotyamu commented on app/models/interview.rb
> +      user = self.user
ここの代入必要かな？ 👀

2019-03-27 02:08 UTC, pokotyamu commented on app/models/interview.rb
> +      end
19~21行目は、一つ一つアップデートを実行せずに、 `interviews.update_all(status: :rejection)` と書くこともできますね！
ただこれにはメリット・デメリットが存在するんですが、分かりますか？

2019-03-27 06:03 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +    if interview.present?
different_userのメソッドなので、unlessですと逆の挙動になってしまいませんか？

2019-03-27 06:05 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +  before_action :correct_user, only: [:destroy]
サンプルアプリの動作に合わせました。

2019-03-27 06:07 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +  before_action :correct_user, only: [:destroy]
サンプルアプリですと、面接官が過去の日時を承認しようとしたときにその日時の編集画面に遷移するようになっていたので、他のユーザーでも編集可能にしました。

2019-03-27 06:10 UTC, tkr-ld commented on config/routes.rb
> +          patch :approve
冪等性を考えるとPUTの方が良いですね。
PUTに修正しました。

2019-03-27 06:13 UTC, tkr-ld commented on app/models/interview.rb
> +    if self.update(status: :approval)
selfがなくても、動作するようなので、修正しました。

2019-03-27 06:16 UTC, tkr-ld commented on app/models/interview.rb
> +    if self.update(status: :approval)
approval!のヘルパーですと、更新に失敗したときに例外を返してしまうため、今回はupdateを用いました。

2019-03-27 06:20 UTC, tkr-ld commented on app/models/interview.rb
> +      user = self.user
コンソールで挙動を確認したところ、代入は必要ないのでこの行は削除しました。

2019-03-27 06:22 UTC, tkr-ld commented on app/models/interview.rb
> +      end
メリットは処理時間が速いこと、デメリットは検証だけでなくコールバックも実行されないことでしょうか？

2019-03-27 06:23 UTC, tkr-ld commented on app/models/interview.rb
> +      end
今回はモデル側でコールバックを使用していないので、`interviews.update_all(status: :rejection)`に修正しました。

2019-03-27 06:31 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    if interview.present?
自分の提案としては、以下のような感じですね！
そもそも使わない `interview` への代入をなくして、取得できなかった場合 `nil` となるので、 `unless` で引っ掛けるという実装です。

```ruby
  def different_user
    unless current_user.interviews.find_by(id: params[:id])
      redirect_to root_url
    end
  end
```

2019-03-27 06:40 UTC, tkr-ld commented on app/models/interview.rb
> +    if self.update(status: :approval)
真偽値で判定するのではなく、例外をキャッチする形にした方が良いでしょうか？

2019-03-27 06:41 UTC, tkr-ld commented
ご指摘いただいた部分を修正しました。
ご確認よろしくお願いします。

2019-03-27 09:58 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +    if interview.present?
自分が何か勘違いしていたら申し訳ないのですが、ここでは`interview`が`nil`になることを前提としているのでやはり逆の動作になってしまうように思います。
以下のようにする方が良いのではと思っています。

```ruby
  def correct_user
    unless current_user.interviews.find_by(id: params[:id])
      redirect_to root_url
    end
  end

  def different_user
    if current_user.interviews.find_by(id: params[:id])
      redirect_to root_url
    end
  end
```

2019-03-28 05:19 UTC, pokotyamu commented on config/routes.rb
> +          patch :approve
> 冪等性

本当に Rails で行っている `#update` メソッドは冪等なんですかね？を考えてもらうのが質問の意図でした。

```
User.first.update(name: 'test')
```

とした時に、更新される値としては `name` カラムだけでなく、 `updated_at` も更新されますよね。
冪等性というのは、常に同じ結果を返すことなので、厳密に言えば冪等ではないです。
なので、 PATCH での実装で問題なかったですね。
ただ、`updated_at` を考えないものと考えると冪等と言えるので、 PUT でも間違いではないと思います。

この違いを理解していただければ、どちらの実装を選んでいただいても良いです！

参考: https://weblog.rubyonrails.org/2012/2/26/edge-rails-patch-is-the-new-primary-http-method-for-updates/

2019-03-28 05:19 UTC, pokotyamu commented on app/models/interview.rb
> +    if self.update(status: :approval)
> selfがなくても動作する

ちなみに、これなんで self なくても動作するんですかね？ 👀 
どんな時に self って必要なんでしょう？ 👀

2019-03-28 05:20 UTC, pokotyamu commented on app/models/interview.rb
> +    if self.update(status: :approval)
> approval!のヘルパーですと、更新に失敗したときに例外を返してしまうため、今回はupdate(status: :approval)を用いました。

あーなるほどね 🙏 
例外をキャッチする方式でもいいですが、今の実装のままでも問題ないです 🙏

2019-03-28 05:22 UTC, pokotyamu commented on app/models/interview.rb
> +      end
> メリットは処理時間が速いこと、デメリットは検証だけでなくコールバックも実行されないため、事前に必要な処理が行われていなくてもSQLが実行される危険性があることでしょうか？

合ってそう 👌 
処理時間が早いのは、 SQL の実行回数が減るからというのがあげられますね。
`update_all` だと1回の SQL 実行で済むところが面接の件数分増えてしまいます。
例えば、 100万件面接が入って時などが考えやすいと思います。

副作用としてはおっしゃる通り、検証やコールバックが実行されないことです。

修正内容としても問題ないように思いました！

2019-03-28 05:25 UTC, pokotyamu commented
> Interviewコントローラのリファクタリング
> Interviewモデルのインスタンスメソッドのリファクタリング

コミットメッセージでは、なぜそのリファクタリングをしたのか？というのを書くようにしましょう。
例えば、インデントがずれていたため直した。とか、 ` after_update` -> `update_success_redirect` にメソッド名を変更した。とか。
コミットメッセージだけみてどんな修正を行ったのかが分かるのが一番良いですね！

2019-03-28 05:47 UTC, pokotyamu commented
おっと前回見落としてたけど、名前無し登録しているユーザーが居ると、ユーザー一覧画面に行けない気がしますね 👀

2019-03-28 06:01 UTC, pokotyamu requested changes
生年月日登録していないユーザーが居た場合、ユーザー一覧ページが開けない不具合を見つけました！
対応よろしくおねがいします 🙏

2019-03-28 06:01 UTC, pokotyamu commented on app/models/user.rb
> +    (Date.today.strftime('%Y%m%d').to_i - birth_date.strftime('%Y%m%d').to_i) / 10000
ここの計算も年齢が入ってない場合に対応できていないかな

2019-03-28 06:10 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    if interview.present?
あーそうか、ごめんなさい自分の勘違いでした 🙇‍♀️ 

`#present?` 抜きで書けますだけで良かったやつでした 🙇 
混乱させてしまってすみませんでした 🙇 

```ruby
  def different_user
    if current_user.interviews.find_by(id: params[:id])
      redirect_to root_url
    end
  end
```

2019-03-28 08:23 UTC, tkr-ld commented on app/models/interview.rb
> +    if self.update(status: :approval)
インスタンスメソッド内でのselfは省略できるためです。
`self.xxx = `のようなセッターメソッドの場合には省略できないようです。
以下の記事を参考にしました。
[rubyでselfを省略できる時、できない時](https://qiita.com/akira-hamada/items/4132d2fda7e420073ab7)

2019-03-28 08:53 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +    if interview.present?
ご確認ありがとうございます。

2019-03-28 08:56 UTC, tkr-ld commented on config/routes.rb
> +          patch :approve
ご教示いただきありがとうございます。
厳密にはPUTではないようなので、PATCHに再度修正しました。

2019-03-28 08:59 UTC, tkr-ld commented
不具合がある状態で提出してしまい、申し訳ありません。
修正しましたので、ご確認よろしくお願いします。

2019-03-29 01:39 UTC, pokotyamu commented on app/models/interview.rb
> +    if self.update(status: :approval)
いいですね 👍 
補足的に self で返ってくるものを見てみるのもいい勉強になると思います！

```ruby
class Human
  def self.aaa
    puts self
  end

  def bbb
    puts self
  end
end


Human.aaa
#=> Human

Human.new.bbb
#=> #<Human:0x00007f84e80bbb88>
```

2019-03-29 01:41 UTC, pokotyamu approved these changes
うん！大丈夫そう！
LGTM です 👍

2019-03-29 01:43 UTC, pokotyamu commented
マージして次に進んでください 😄 

![](https://media.giphy.com/media/3o7abB06u9bNzA8lu8/giphy.gif)

2019-03-29 08:21 UTC, merged