面談日程の承認依頼申請メールと承認メールの送信機能の実装
tkr-ld/e-navigator pull request #11
Opened 2019-04-01 01:03 UTC by tkr-ld

やりたかったこと
---
- 指定したユーザーに希望する面談日程の承認を依頼するメール送信機能の実装
- 承認が押された際に、承認者と申請者にメールを送信する機能の実装

やったこと
----
- letter_opener_web gemの導入
- dotenv-rails gemの導入
- 環境変数の設定
- 面接日時確定メールの送信機能の実装
- 承認依頼申請メールの送信機能の実装
- 全体的なビューの微調整

動作確認方法
---
- [ ] 自分の面接一覧からメールアドレスを指定し、面接日程の承認を申請する
- [ ] 指定したメールアドレスにメールが届いているか確認する
- [ ] 指定したメールアドレスでログインする
- [ ] ユーザー一覧から申請元の面接一覧にいく
- [ ] 面接日程を確定する
- [ ] 両者に違う文面でメールが届いていることを確認する

その他
---
よろしくお願いします。

2019-04-02 08:33 UTC, pokotyamu requested changes
主に名前つけについてレビューしています 🙋‍♂️ 
検討よろしくおねがいします！

2019-04-02 08:33 UTC, pokotyamu commented on Gemfile
> +gem 'letter_opener_web', group:  :development
37行目からの `development` グループの中にまとめられそう 👀

2019-04-02 08:33 UTC, pokotyamu commented on app/mailers/approval_application_mailer.rb
> +class ApprovalApplicationMailer < ApplicationMailer
ここの主語としては、「面接」に関するメールだと思うので、 `InterviewMailer` の方が適切なんじゃないかなと思います！
クラス名はあくまでも操作するオブジェクトが来る方がいいですね！

2019-04-02 08:33 UTC, pokotyamu commented on app/mailers/approval_application_mailer.rb
> +  def application_email(approver,current_user)
`Mailer` クラスなので、メソッド名に `_email` というサフィックスは自明なので、要らない気がしますね 👀

2019-04-02 08:33 UTC, pokotyamu commented on app/mailers/approval_application_mailer.rb
> +  def approval_email_for_applicant(interview,current_user)
`for_applicant` などの「誰が使うか？」という情報はメソッドを使う側の問題だと思うので、メソッド名としてあまり適切ではないかなと思いました。
メッセージの切り替えはそんなに気にせずでもいいのかなとも思ったり 🤔

2019-04-02 08:33 UTC, pokotyamu commented on app/mailers/approval_application_mailer.rb
> +  def approval_email_for_applicant(interview,current_user)
分けたい場合はどんな名前つけが適切だろうか 💭 
そうなってくると `ApprovalInterviewMailer` クラスの `#interviewer` と `#interviewee` みたいな感じかな？ 🤔 
それはそれでありな気がしてきた。

2019-04-02 08:33 UTC, pokotyamu commented on config/routes.rb
> +      end
collection での追加良いですね 👍

2019-04-02 08:33 UTC, pokotyamu commented on config/routes.rb
> +  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
`LetterOpenerWeb` の使い方バッチリですね 👍

2019-04-02 08:33 UTC, pokotyamu commented on app/mailers/approval_application_mailer.rb
> +  def approval_email_for_applicant(interview,current_user)
思い切って
`ApprovalInterviewMailer` クラスと `ApplyInterviewMailer` クラスで分けるというのはどうでしょうか？

2019-04-02 08:33 UTC, pokotyamu commented on app/mailers/approval_application_mailer.rb
> +  def application_email(approver,current_user)
`current_user` かどうかより、 `current_user` が面接官なのか、面談者なのかの方がメソッドの引数としては重要なんじゃないかなと思いました！
面談者が `current_user` にするかどうかは、呼び出す側の都合なので！

2019-04-02 12:35 UTC, tkr-ld commented on Gemfile
> +gem 'letter_opener_web', group:  :development
修正しました。

2019-04-02 12:38 UTC, tkr-ld commented on app/mailers/approval_application_mailer.rb
> +  def approval_email_for_applicant(interview,current_user)
`ApproveInterviewMailer` クラスと `ApplyInterviewMailer` クラスに分けました。
最初の部分を動詞に統一し、`Approve`としました。

2019-04-02 12:44 UTC, tkr-ld commented on app/mailers/approval_application_mailer.rb
> +  def application_email(approver,current_user)
確かに`current_user`だと申請と承認の場合で面接官と面談者が入れ替わってしまうのでわかりにくいですね。
`current_user`を`approver`と`applicant`に変更しました。
`interviewer`と`inteviewee`はメソッド名で使っているため、わかりづらくなると思い、メソッド内で使うのは避けました。

2019-04-02 12:48 UTC, tkr-ld commented on app/mailers/approval_application_mailer.rb
> +  def approval_email_for_applicant(interview,current_user)
`interviewer`と`interviewee`に変更しました。

2019-04-02 12:52 UTC, tkr-ld commented
お忙しい中レビューをしていただき、本当にありがとうございました。
ご指摘いただいた箇所を修正しましたので、ご確認よろしくお願いいたします。

2019-04-04 04:09 UTC, pokotyamu approved these changes
うん！いい感じに修正できてますね 😄 
動きも問題無さそう！
LGTM です 🎉

2019-04-04 04:09 UTC, pokotyamu commented on app/mailers/apply_interview_mailer.rb
> +  end
メソッド内のインデントがズレている気がしますね 👀 
エディターの機能で保存時にインデントを直したりということも可能だと思うので調べてみて入れても良いかもですね！

2019-04-04 04:13 UTC, pokotyamu commented
インデントの部分は直してマージしてください！
e-Navigator 完走お疲れ様でした！！！！！
![giphy](https://user-images.githubusercontent.com/3479317/55529243-54ad9780-56db-11e9-81e8-5d0dfb814b2d.gif)

2019-04-04 05:44 UTC, tkr-ld commented
インデントを直しましたのでマージいたします。
約3週間丁寧にレビューしていただき、本当にありがとうございました。
独学だけでは分からない多くのことを学ぶことができました。
フィードバック面談もよろしくお願いいたします。

2019-04-04 05:44 UTC, merged