#1 前編
tkr-ld/e-navigator pull request #8
Opened 2019-03-11 02:06 UTC by tkr-ld

やりたかったこと
---
- ユーザー登録、ログイン機能の追加
- 登録したユーザーのプロフィール編集機能の追加
- Bootstrapを用いて、デザインの変更

やったこと
----
- Devise gem の導入
- テンプレートエンジンをslimに変更
- Bootstrapの導入
- 後半でトップページではユーザー一覧を行うように実装するため、現段階ではトップページは自動生成されるUsers#indexに設定
- enum_help gemの導入
- フラッシュ・フォーム関連の日本語対応
- プロフィール編集機能の追加（性別はenum使用）

動作確認方法
---
- [ ] ユーザーを新規で作成する
- [ ] ユーザーの詳細ページにいく
- [ ] ユーザーの登録情報を変更する
- [ ] ログアウトする
- [ ] ログアウトしている状態で、https://e-navigator-tkr-ld.herokuapp.com/users/edit に遷移しようとしたときにログインページにリダイレクトされることを確認する

その他
---
よろしくお願いします。

2019-03-13 01:56 UTC, pokotyamu commented
👀

2019-03-13 02:02 UTC, pokotyamu commented
Github の使い方
---

`#1 前編` というタイトルだと、３ヶ月後に何をやったプルリクエストかぱっと見分からなくなるので
`ログイン・ユーザー登録`

2019-03-13 02:04 UTC, pokotyamu commented
git の使い方
---

こちらも https://github.com/tkr-ld/e-navigator/pull/8#issuecomment-472250049 と同じように、そのコミットで何をしたか分かるように書いたほうが良いですね。
`前半-1`、`前半-2`、`前半-3` となっているそれぞれは何をしたかったのか？というのをコミットメッセージに書くのがいいです！

ブランチ名も同様。

2019-03-13 02:05 UTC, pokotyamu commented
こちら git の使い方の参考になると思うので、ぜひ読んでみてください！
 [【初心者向け】「コミットの粒度がわからない問題」の模範解答を考えてみた - Qiita](https://qiita.com/jnchito/items/40e0c7d32fde352607be)

2019-03-13 02:17 UTC, pokotyamu commented
カスタマイズしないで生成されたそのままを使うのであれば、 devise 系のコントローラーは不要なはずですね！
消すかどうかはお任せします 👌

2019-03-13 02:19 UTC, pokotyamu requested changes
基本的な動作は問題なさそうなことを確認しました 👍 
devise 上手く使えていると思います！
yml のコメントと、最終行の改行とこのプルリクエストのタイトルだけ直したらまたご連絡ください 🙏

2019-03-13 02:19 UTC, pokotyamu commented on Gemfile
> +gem 'enum_help'
ソースコードの最終行には改行を入れるようにしましょう！
エディタの設定で追加しておくと良いと思います！

[なぜ最終行に改行が必要なのか - komagataのブログ](http://docs.komagata.org/5460)

2019-03-13 02:19 UTC, pokotyamu commented on app/models/user.rb
> +  validates :school, length: {maximum: 50}
バリデーション設定良いですね 👍

2019-03-13 02:19 UTC, pokotyamu commented on devise.ja.yml
> +#      not_found: "not found"
基本的に `xxx.ja.yml` は日本語を扱うはずなので、英語名のコメントはいらないですね。
`xxx.en.yml` に書くべきだと思います！

2019-03-13 06:17 UTC, tkr-ld commented
ご指摘いただいたdevise.ja.ymlについては作業していた過程で削除し忘れていたものだったので削除しました。
実際に使用しているファイルはconfig\locales\devise.ja.ymlです。

2019-03-13 06:30 UTC, tkr-ld commented
devise系のコントローラーについては、デフォルトでプロフィール編集の際にパスワードの確認が必要だったため、パスワードを入力しなくて済むように一部カスタマイズしています。(registrations_controller.rbに記述しています)

2019-03-18 03:35 UTC, pokotyamu commented
> devise系のコントローラーについては、デフォルトでプロフィール編集の際にパスワードの確認が必要だったため、パスワードを入力しなくて済むように一部カスタマイズしています。

おっとすみません 🙏 
見落としてました 🙏

2019-03-18 03:36 UTC, pokotyamu commented
タイトルの調整良いですね 👍 
次のプルリクエストも名前つけに気をつけて、よろしくおねがいします！

2019-03-18 03:37 UTC, pokotyamu approved these changes
遅くなって大変申し訳ありませんでした🙏
コード動作ともに問題ないことを確認したので、マージして次に進んでください！

2019-03-18 07:24 UTC, merged

2019-03-18 07:25 UTC, tkr-ld commented
レビューありがとうございました。