面接日程の表示、登録、編集、削除機能の実装
tkr-ld/e-navigator pull request #9
Opened 2019-03-20 00:58 UTC by tkr-ld

やりたかったこと
---
- 面接日程の表示、登録機能の実装
- 面接日程の編集、削除機能の追加

やったこと
----
- Interviewモデルの作成(承認状態はenum使用)
- 面接日程の表示、登録機能の実装
- 面接日程の編集、削除機能の追加（登録したユーザーのみ操作が行えるように）
- 前回のプルリクエストで行えていなかったパスワード再設定画面の日本語化、Bootstrapの適用

動作確認方法
---
- [ ] ログインし、自分の面接一覧にいく
- [ ] 面接の登録、編集、削除を行う
- [ ] 面接一覧から正しく操作が行われていることを確認する
- [ ] 他ユーザーの面接一覧（https://e-navigator-tkr-ld.herokuapp.com/users/1/interviews）にいく
- [ ] 編集や削除を行おうとするとトップページのUsers#indexにリダイレクトされることを確認する

その他
---
現段階では他ユーザーの面接一覧画面から新規登録を行うことができますが、実際に登録されるのはログインしているユーザーの面接日時になります。
よろしくお願いします。

2019-03-20 09:49 UTC, pokotyamu commented
コミットメッセージめっちゃ良くなってますね 👍 👍

2019-03-20 09:50 UTC, pokotyamu requested changes
気になる点をコメントしました！
修正よろしくおねがいします！

2019-03-20 09:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @user = User.find(params[:user_id])
各所で `@user = User.find(params[:user_id])` という実装がありますね 👀 
Rails には繰り返し同じ実装をしないようにしましょうという DRY 原則というものがあります！
`set_user` などメソッド化してしまって、コールバック関数にまとめちゃいましょう 👍

2019-03-20 09:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find_by(id: params[:id])
ここって、インスタンス変数に入れているのってなんか意味ありますか？ 👀

2019-03-20 09:50 UTC, pokotyamu commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find_by(id: params[:id])
このメソッドでやりたいことは、ユーザー本人かの確認だと思うので、 `@interview` への代入は他でもいいかなと思った次第です。

2019-03-20 09:50 UTC, pokotyamu commented on app/models/user.rb
> +  has_many :interviews
このままだと、ユーザーに紐づく面接が存在する場合、ユーザーを削除することができませんね 👀 
削除時に連動して関係するレコードを削除するように修正してください！

2019-03-22 02:45 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find_by(id: params[:id])
@interviewへの代入まで行いたかったため、インスタンス変数にしていました。(通常の変数だと値渡しになってしまうためか、inteview.destroyが上手くいきませんでした)

2019-03-22 02:47 UTC, tkr-ld commented on app/controllers/interviews_controller.rb
> +    @interview = current_user.interviews.find_by(id: params[:id])
ここでは通常の変数に変更し、@interviewの代入はset_userとして別のコールバック関数として呼び出すように変更しました。

2019-03-22 02:48 UTC, tkr-ld commented
ご指摘いただいた箇所を修正しました。
よろしくお願いします。

2019-03-25 01:52 UTC, pokotyamu commented
> コードレビュー修正、主にInterviewコントローラのリファクタリング

これを一コミットにまとめてしまうのは良くないですね 😓 
コミットは「リファクタリングを行った」ことより「どんなリファクタリングを行った」のか？を書くべきです。
そして、やってる内容として、 Controller のリファクタリングと、ユーザーと連動して削除される機能の追加は違うものなので、コミットを分けて実装すべきだと思いました！

2019-03-25 01:54 UTC, pokotyamu commented
今一度、この記事の動画を見直すことをおすすめします！
[【初心者向け】「コミットの粒度がわからない問題」の模範解答を考えてみた - Qiita](https://qiita.com/jnchito/items/40e0c7d32fde352607be)

2019-03-25 01:56 UTC, pokotyamu commented
プルリクエストの粒度も含めて、フィードバック面談の時にお話します 🙏

2019-03-25 01:56 UTC, pokotyamu approved these changes
実装内容的には問題無さそう 👌

2019-03-25 05:17 UTC, merged